import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/general/footer";
import Nav from "@/components/general/navbar/nav";
import { AuthProvider } from "@/contextAPI/authContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
        <Nav/>
        <div className="min-h-[calc(100vh-66px)]">
      {children}
    </div>
        <Footer/>
        </AuthProvider>

        </body>
    </html>
  );
}
